---
title: "Personal"
---

## Background

I grew up in Denver, Colorado then headed East to go to college. In 1985, I earned my B.A. in Cognitive Science at Brown University. After graduation, I worked in Washington, DC for several non-profit organizations doing fundraising, public relations, and volunteer management. For a short time I was an international trade and public affairs consultant. In 1992, I started graduate school, earning my M.S. and Ph.D. degrees in Psychology at Carnegie Mellon University where I focused on developmental cognitive neuroscience. I also participated in the Center for the Neural Basis of Cognition (CNBC) Graduate Training Program. I moved to State College in 1997. I am married and have two daughters.

## Activities

For fun, I like to walk, run, hike, backpack, kayak and ride my bicycles: a foldable touring Bike Friday, a Specialized Hybrid that I sometimes use to commute to work, and stoker-willing, a road tandem we call Tonya.

I have been involved in local politics, serving as clerk and Judge of Elections in my State College precinct. I was a moderate Republican for many years, but changed parties more than a decade ago. My wife and I were formerly Democratic Precinct Co-chairs.

My family and I are involved in local theatre. Recent shows have included "Oliver!", "The Sound of Music," and "Sweeney Todd," with Singing Onstage, "Dracula", "The Survivor", and "Gypsy" with the State College Community Theatre (SCCT), and "The Memory of Water" and "Harper Regan" with The Next Stage theatre company. I am former president of SCCT.

Needless to say, I love to sing and dance. I'm also learning to play a number of instruments, including the banjo, mandolin, harmonica, and tin whistle.

I'm a bit of a techno-geek (Mac, iPhone, iPad), and play around with electronics from time to time -- you can say Arduino to me and I'll say Uno. 

I am a ham (amateur) radio operator, General class, with callsign K3ROG. I enjoy ragchewing on the local 2m repeater, emergency/event communications, and am slowly learning the ins and outs of HF DXing using my new IC-7300.

Finally, I keep a [blog](http://rick-gilmore.com) where I share poetry, essays, and occasionally photography.
